// enColumnDescriptions.ts

export const EN_COLUMN_DESCRIPTIONS: Record<string, { header: string; cell: string }> = {

    // ----------------------------------------------------------------------
    // --- Identity / General Columns ---
    // ----------------------------------------------------------------------
    strategy: {
        header: "Name, ticker, and quick links for the NFT Collection associated with the strategy.",
        cell: "Displays the collection image, token symbol, and links to the strategy page, contract, and OpenSea.",
    },
    actions: {
        header: "Available actions for the strategy (e.g., maximizing details).",
        cell: "Allows navigation to the detailed strategy page for in-depth analysis.",
    },

    // ----------------------------------------------------------------------
    // --- Price / Volume Metrics ---
    // ----------------------------------------------------------------------
    price: {
        header: "Current price of the strategy's token, converted to USD.",
        cell: "The price is based on the latest known trade of the token: ${{price_usd}}.",
    },
    priceChange24h: {
        header: "Percentage change in the token price over the last 24 hours.",
        cell: "Volatility indicator: Green for a rise, Red for a fall. Current 24h change: {{change_percent}}.",
    },
    volume24h: {
        header: "Total transaction volume (buy and sell) over the last 24 hours in USD.",
        cell: "The aggregated trade volume for the collection during the last 24 hours: ${{volume_usd}}.",
    },

    // ----------------------------------------------------------------------
    // --- Trading / PnL Metrics ---
    // ----------------------------------------------------------------------
    buyVolume: {
        header: "Total volume (in ETH) and number of purchases made by this strategy over the period.",
        cell: "Indicates the strategy's buying pressure: {{volume_eth}} ETH over {{tx_count}} transactions.",
    },
    saleVolume: {
        header: "Total volume (in ETH) and number of sales made by this strategy over the period.",
        cell: "Indicates the strategy's selling pressure: {{volume_eth}} ETH over {{tx_count}} transactions.",
    },
    realizedPnL: {
        header: "Realized Profit/Loss (PnL) generated by the strategy (in ETH).",
        cell: "Calculated PnL on closed trades (sales). Does not account for assets in inventory. PnL: {{pnl_eth}} ETH.",
    },

    // ----------------------------------------------------------------------
    // --- Inventory / Balance ---
    // ----------------------------------------------------------------------
    treasury: {
        header: "Total value (in USD) of the NFT inventory held by the strategy contract.",
        cell: "The value is estimated based on the floor price of the {{nft_count}} NFTs currently in inventory. Total value: ${{value_usd}}.",
    },
    currentBalance: {
        header: "Current balance of the strategy's account (in ETH), used for trading.",
        cell: "The available ETH balance ({{balance_eth}} ETH). The percentage ({{completion_percent}}) indicates the current balance relative to the target or initial balance.",
    },

    // ----------------------------------------------------------------------
    // --- Strategy Token Metrics (Strat) ---
    // ----------------------------------------------------------------------
    stratMcap: {
        header: "Market capitalization of the strategy token (Strategy Market Cap).",
        cell: "This figure represents the total value of the strategy tokens in circulation: ${{market_cap_usd}}.",
    },
    stratHolders: {
        header: "Total number of unique wallets holding the strategy token.",
        cell: "The strategy token is currently held by {{holders_count}} unique addresses.",
    },
    burn: {
        header: "Percentage of strategy tokens that have been permanently burned.",
        cell: "The token supply has been reduced by {{burned_percent}} through burning mechanisms.",
    },

    // ----------------------------------------------------------------------
    // --- Fees ---
    // ----------------------------------------------------------------------
    feesStrat: {
        header: "Total fees (in ETH) accrued by the strategy owner/developer.",
        cell: "Amount of {{fees_eth}} ETH paid as Strategy Fees.",
    },
    feesPnkstr: {
        header: "Total fees (in ETH) accrued by the platform (PNKSTR).",
        cell: "Amount of {{fees_eth}} ETH paid as Platform Fees.",
    },
    feesRoyalties: {
        header: "Total royalties (in ETH) paid to the NFT collection creators.",
        cell: "Amount of {{fees_eth}} ETH paid as Collection Royalties.",
    },

    // ----------------------------------------------------------------------
    // --- NFT Collection Metrics ---
    // ----------------------------------------------------------------------
    nftFloor: {
        header: "Current floor price (lowest price) of the associated NFT collection (in ETH).",
        cell: "The lowest listed price for an NFT in the collection is {{floor_eth}} ETH.",
    },
    nftMcap: {
        header: "Market capitalization of the associated NFT collection (NFT Market Cap).",
        cell: "The total market value of the NFT collection is estimated at ${{market_cap_usd}}.",
    },
    nftHolders: {
        header: "Total number of unique wallets holding the associated NFT collection.",
        cell: "The collection is held by {{holders_count}} unique NFT holders.",
    },

    // ----------------------------------------------------------------------
    // --- Ecosystem Token Metrics (Eco) ---
    // ----------------------------------------------------------------------
    ecoToken: {
        header: "Ticker and current price of the secondary ecosystem token.",
        cell: "Ecosystem Token Ticker: {{ticker}}. Price: ${{price_usd}}.",
    },
    ecoMcap: {
        header: "Market capitalization of the secondary ecosystem token.",
        cell: "The ecosystem token's total market value is ${{market_cap_usd}}.",
    },
    ecoHolders: {
        header: "Total number of unique wallets holding the secondary ecosystem token.",
        cell: "The ecosystem token is held by {{holders_count}} unique addresses.",
    },

    // ----------------------------------------------------------------------
    // --- Ratios / Depth ---
    // ----------------------------------------------------------------------
    ecoColRatio: {
        header: "Ecosystem Token Collateralization Ratio (Eco/NFT).",
        cell: "The ratio representing the collateral backing of the ecosystem token supply: {{ratio_percent}}.",
    },
    navRatio: {
        header: "Net Asset Value (NAV) Ratio of the strategy token. (=MCAP/Treasury)",
        cell: "A ratio of {{ratio_x}}x, comparing the token price to the underlying Net Asset Value per token.",
    },
    ecoColHolderRatio: {
        header: "Ratio of unique ecosystem token holders vs. NFT collection holders.",
        cell: "Measures the overlap or distinction between the two holder bases: {{ratio_percent}}.",
    },
    ecoStratHolderRatio: {
        header: "Ratio of unique ecosystem token holders vs. Strategy token holders.",
        cell: "Measures the overlap or distinction between the two token holder bases: {{ratio_percent}}.",
    },
    stratColHolderRatio: {
        header: "Ratio of unique Strategy token holders vs. NFT collection holders.",
        cell: "Measures the overlap or distinction between the two holder bases: {{ratio_percent}}.",
    },
    marketDepthKPIs: {
        header: "Key Market Depth Indicators (Dominance/Selling Wall).",
        cell: "Displays the listing volume ({{volume_eth}} ETH, {{count}} listings) for the dominant selling wall or the strategy's current listing position.",
    }
};